name: tager
description: "Tager ERP - Wholesale Trade & POS Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Database
  drift: ^2.24.0
  sqlite3_flutter_libs: ^0.5.28

  # Routing
  go_router: ^15.1.2

  # Code Gen Annotations
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # UI
  fl_chart: ^0.70.2
  data_table_2: ^2.5.16
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_svg: ^2.0.17
  lucide_icons: ^0.257.0

  # Reports
  pdf: ^3.11.3
  printing: ^5.13.5

  # Utils
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  intl: ^0.20.2
  uuid: ^4.5.1
  path: ^1.9.1
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.24.0
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/sounds/

